### ISSUE TITLE
End of Project Checklist

### ISSUE THREAD

**Issue by CHarvey820** [tetrominoes/Issues#16]
**Team Culture:**
- [ ] Build team culture through non-work activities.
- [x] Regularly recognize and complement team members for their contributions.
- [x] Respectfully provide coaching to improve team effectiveness and efficiency.

**Communication:**
- [x] Set up and use communication tools and processes for effective and rapid information exchange. 
  Slack
- [x] Use these tools and processes regularly.
- [x] Establish and use remote communication tools and processes for distributed team interactions.
Google Hangouts
- [x] Establish and use initiation and exit checklists.            https://github.com/tetrominoes/Issues/issues/4
- [x] Establish and use team policy statement. https://github.com/tetrominoes/Issues/blob/master/TeamPolicy.md

**Requirements and Analysis:**
- [ ] Create user stories to capture basic product requirements.
- [ ] Analyze, refine, prioritize, select and convert user stories into tasks for development.
- [ ] Organize tasks into Epic-story-task packages.
- [ ] Experiment with Job Stories as an alternative to User Stories (see https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [x] Created basic design documents such as class, interaction and use case.
https://drive.google.com/file/d/1Fheif9J3LxQ07mz618gkrWQCvONNhhrT/view?usp=sharing
- [ ] Wrote lightweight design documents
- [ ] Wrote throw-away prototype code to explore high-risk design elements.

**Development:**
- [x] Create GitHub Issues describing major design and development tasks.
https://github.com/tetrominoes/Issues/projects/1
- [x] Establish GitHub Project (Kanban) board.
https://github.com/tetrominoes/Issues/projects/1
- [x] Actively manage work by tracking issues on your Kanban board.
- [x] Conduct regular project meetings to assess progress and manage schedule.
- [ ] Use code formatting tool to assure uniform source code.
- [ ] Identify and use a coding convention.
- [ ] Develop in-source documentation via Doxygen.

**Testing:**
- [x] Create basic test capabilities.
-print statements within methods
- [x] Create comprehensive test capabilities.
-begin a test suite
- [ ] Create and regularly use unit testing.
- [ ] Use a pull-request, code-review integration process for source changes.
- [ ] Automatically monitor and report code coverage.
- [ ] Use test-driven development.
- [ ] Measure and track software performance.

**Product Release:**
- [ ] Create a unique and traceable release of your software product.
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [ ] Generate user and developer documentation.
- [ ] Create product branding, e.g. logo family, catchphrase, product description.
