### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jesshansen** [tetrominoes/Issues#22]
[Presentation](https://docs.google.com/presentation/d/1wzz_ijRQqxc1RA-lT_5ftHkl8TjYeC1sAL3WaGk0Qnc/edit?usp=sharing)
- [ ] Build team culture through non-work activities.
- [x] Regularly recognize and complement team members for their contributions.
- [x] Respectfully provide coaching to improve team effectiveness and efficiency.

**Communication:**
- [x] Set up and use communication tools and processes for effective and rapid information exchange.
Slack/Hangouts
- [x] Use these tools and processes regularly.
- [x] Establish and use remote communication tools and processes for distributed team interactions.
- [x] Establish and use initiation and exit checklists.
https://github.com/tetrominoes/Issues/issues/4
https://github.com/tetrominoes/Issues/issues/9
- [x] Establish and use team policy statement.
https://github.com/tetrominoes/Issues/blob/master/TeamPolicy.md

**Requirements and Analysis:**
- [x] Create user stories to capture basic product requirements.
- [x] Analyze, refine, prioritize, select and convert user stories into tasks for development.
- [ ] Organize tasks into Epic-story-task packages.
- [ ] Experiment with Job Stories as an alternative to User Stories (see https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [x] Create basic design documents such as class, interaction and use case.
https://drive.google.com/file/d/1Z6twe7BPpQeklmzxSN5UHIVEsnzGvLex/view?usp=sharing (very basic)
- [ ] Write lightweight design documents
- [ ] Write throw-away prototype code to explore high-risk design elements.

**Development:**
- [x] Create GitHub Isses describing major design and development tasks.
https://github.com/tetrominoes/Issues/issues
- [x] Establish GitHub Project (Kanban) board.
https://github.com/tetrominoes/Issues/projects/2
- [x] Actively manage work by tracking issues on your Kanban board.
- [x] Conduct regular project meetings to assess progress and manage schedule.
- [ ] Use code formatting tool to assure uniform source code.
- [x] Identify and use a coding convention.
- [ ] Develop in-source documentation via Doxygen.

**Testing:**
- [x] Create basic test capabilities.
- [ ] Create comprehensive test capabilities.
- [ ] Create and regularly use unit testing.
- [ ] Use a pull-request, code-review integration process for source changes.
- [ ] Automatically monitor and report code coverage.
- [ ] Use test-driven development.
- [x] Measure and track software performance.

**Product Release:**
- [ ] Create a unique and traceable release of your software product.
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [x] Generate user and developer documentation.
- [x] Create product branding, e.g. logo family, catchphrase, product description.
