### ISSUE TITLE
Initiation Checklist

### ISSUE THREAD

**Issue by tetrominoes** [tetrominoes/Issues#4]
- [ ] Create individual GitHub account (If you don't have one) and connect it to the group repo.
- [ ] Familiarize yourself with the Project Board and relative source code.
- [ ] Create Slack account.
- [ ] Get added to Tetrominoes Slack.
- [ ] Become a member of the group Google Drive.
- [ ] Review Tetrominoes Policies.
- [ ] Let us know about any strengths or weaknesses you have.
- [ ] Discuss policies, repositories and group accounts with the group to ensure the best understanding of your new group dynamic.
- [ ] Familiarize yourself with Cloud9 IDE
