### ISSUE TITLE
Jess Hansen Initiation Checklist

### ISSUE THREAD

**Issue by jesshansen** [tetrominoes/Issues#8]
- [x] Create individual GitHub account (If you don't have one) and connect it to the group repo.
- [x] Familiarize yourself with the Project Board and relative source code.
- [x] Create Slack account.
- [x] Get added to Tetrominoes Slack.
- [x] Become a member of the group Google Drive.
- [x] Review Tetrominoes Policies.
- [x] Let us know about any strengths or weaknesses you have.
